### ISSUE TITLE
Homepage keeps crashing (S21 Ultra) 

### ISSUE THREAD

**Issue by JaxzKyd** [musicorum-app/mobile#14]
Noticed the app on the Play Store legit 5 minutes ago and was like "ayy Musicorum? How could I not, those mfs have the best charts and their rewinds are godsend" 🙏🏾

Unfortunately however, the home page keeps crashing on my device (Samsung S21 Ultra 5G) a few seconds after opening the app. If I click on one of the other tabs before it crashes though, those pages work fine without crashing, it's literally only the home page.

**Comment by LuckShiba** [comment]
Try to clear the app data, I was with the same problem and after a reset it worked like a charm

**Comment by JaxzKyd** [comment]
Cleared the app data, still crashing unfortunately 😔

**Comment by MysteryMS** [comment]
Apologies for the late response. I just saw the issue. Sorry I couldn't be of more help earlier.
Since February 6th I believe this should be already fixed.
Let me know how it goes, @JaxzKyd
And thanks for the positive feedback about our charts and Rewind! <3

Once again, my sincere apologies for replying this just now.

**Comment by JaxzKyd** [comment]
It's no problem! And yeah no more crashes 😁
Thank you and keep up the amazing work!
